version: '3.8'

services:
  eureka:
    build: ./eureka
    image: medaminekalai/prj-back-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    build: ./config-server
    image: medaminekalai/prj-back-config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  trainings-service:  # <- Ton service doit être bien aligné sous services
    build: ./microservices/trainings
    image: medaminekalai/prj-back-trainings-service:latest
    container_name: trainings-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - config-server
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservices-network

networks:
  microservices-network:
