/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Annonce } from '../../models/annonce';

export interface GetAnnoncesAujourdhui$Params {
}

export function getAnnoncesAujourdhui(http: HttpClient, rootUrl: string, params?: GetAnnoncesAujourdhui$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Annonce>>> {
  const rb = new RequestBuilder(rootUrl, getAnnoncesAujourdhui.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Annonce>>;
    })
  );
}

getAnnoncesAujourdhui.PATH = '/api/annonces/aujourdhui';
