/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Annonce } from '../../models/annonce';

export interface GetAnnoncesCetteSemaine$Params {}

export function getAnnoncesCetteSemaine(
  http: HttpClient,
  rootUrl: string,
  params?: GetAnnoncesCetteSemaine$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<Annonce>>> {
  const rb = new RequestBuilder(rootUrl, getAnnoncesCetteSemaine.PATH, 'get');
  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<Array<Annonce>>)
  );
}

getAnnoncesCetteSemaine.PATH = '/api/annonces/semaines';
