/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Annonce } from '../../models/annonce';

export interface ModifierAnnonce$Params {
  id: number;
      body: Annonce
}

export function modifierAnnonce(http: HttpClient, rootUrl: string, params: ModifierAnnonce$Params, context?: HttpContext): Observable<StrictHttpResponse<Annonce>> {
  const rb = new RequestBuilder(rootUrl, modifierAnnonce.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Annonce>;
    })
  );

}

modifierAnnonce.PATH = '/api/annonces/{id}';
