/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Annonce } from '../../models/annonce';

export interface RechercherAnnonces$Params {
  titre?: string;
  categoryId?: number;
  statut?: 'EN_ATTENTE' | 'APPROUVEE' | 'REJETEE';
}

export function rechercherAnnonces(http: HttpClient, rootUrl: string, params?: RechercherAnnonces$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Annonce>>> {
  const rb = new RequestBuilder(rootUrl, rechercherAnnonces.PATH, 'get');
  if (params) {
    rb.query('titre', params.titre, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Annonce>>;
    })
  );
}

rechercherAnnonces.PATH = '/api/annonces/rechercher';
