/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Annonce } from '../../models/annonce';

export interface ValiderAnnonce$Params {
  id: number;
}

export function validerAnnonce(http: HttpClient, rootUrl: string, params: ValiderAnnonce$Params, context?: HttpContext): Observable<StrictHttpResponse<Annonce>> {
  const rb = new RequestBuilder(rootUrl, validerAnnonce.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Annonce>;
    })
  );
}

validerAnnonce.PATH = '/api/annonces/{id}/valider';
