/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface Annonce {
  category?: Category;
  datePublication?: string;
  description?: string;
  email?: string;
  id?: number;
  statut?: 'EN_ATTENTE' | 'APPROUVEE' | 'REJETEE';
  titre?: string;
}
