/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Annonce } from '../models/annonce';
export interface Category {
  annonces?: Array<Annonce>;
  id?: number;
  nom?: string;
}
